let constants = (accounts) => {
  return {
    agent1: accounts[0],
    agent2: accounts[1],
    patron1: accounts[2],
    patron2: accounts[3],
    provider1: accounts[4],
    providerName1: 'TheFirstProvider',
    provider2: accounts[5],
    providerName2: 'TheSecondProvider',
    provider3: accounts[6],
    providerName3: 'TheThirdProvider',
    provider4: accounts[7],
    providerName4: 'TheFourthProvider',
    pharmacy1: accounts[8],
    pharmacyName1: 'TheFirstPharma',
    family1: accounts[9],
    familyName1: 'Fam1',
    family2: accounts[10],
    familyName2: 'Fam2',
    perm1: 'bloodtest',
    permIndex1: 0,
    perm2: 'radiology',
    permIndex2: 1,
    perm3: 'xrays',
    permIndex3: 2,
    canRead: true,
    cannotRead: false,
    canWrite: true,
    cannotWrite: false,
    duration0: 0,
    durationForever: 100000,
    duration1: 50,
    host1: '0.0.0.0',
    host2: '127.0.0.1',
  };
};

module.exports = constants;
