const SET_USER = 'SET USER';
const CLEAR_USER = 'CLEAR USER';
const SET_RELATIONSHIP = 'SET RELATIONSHIP';
const SET_VIEWER = 'SET VIEWER';
const CLEAR_RELATIONSHIP = 'CLEAR RELATIONSHIP';

export {SET_USER, CLEAR_USER, SET_RELATIONSHIP, SET_VIEWER, CLEAR_RELATIONSHIP};
